# Generated by Django 4.2.24 on 2025-09-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "mbid",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz ID",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "albums",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "mbid",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz ID",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "artists",
            },
        ),
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_sync_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful sync",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("syncing", "Syncing"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_status",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "mbid",
                    models.CharField(
                        blank=True,
                        help_text="MusicBrainz ID",
                        max_length=36,
                        null=True,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Track duration in seconds", null=True
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
            },
        ),
        migrations.CreateModel(
            name="Scrobble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When the track was played"),
                ),
                (
                    "lastfm_reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from Last.fm API",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrobbles",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "db_table": "scrobbles",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="artists_name_b2ca99_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["mbid"], name="artists_mbid_1203a9_idx"),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="music.artist",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["name"], name="tracks_name_8e31d5_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["artist"], name="tracks_artist__26fd8f_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["album"], name="tracks_album_i_8d2ff6_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["mbid"], name="tracks_mbid_a3b899_idx"),
        ),
        migrations.AddIndex(
            model_name="scrobble",
            index=models.Index(
                fields=["timestamp"], name="scrobbles_timesta_fda7b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrobble",
            index=models.Index(fields=["track"], name="scrobbles_track_i_ba1630_idx"),
        ),
        migrations.AddIndex(
            model_name="scrobble",
            index=models.Index(
                fields=["lastfm_reference_id"], name="scrobbles_lastfm__6927bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["name"], name="albums_name_fbf363_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["artist"], name="albums_artist__2d0263_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["mbid"], name="albums_mbid_3ed90b_idx"),
        ),
    ]
